version: '3.8'

services:
  reverse-proxy:
# Stable alpine pour une version moins lourde de nginx
    image: nginx:stable-alpine
    container_name: reverse-proxy
    volumes:
      -./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      -"443:443"
    depends_on:
      - frontend
      - user-profile
      - game
    networks:
      - web

  frontend:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - web
    depends_on:
      - user-profile
      - game

  user-profile:
    build:
      context: ../services/user-profile
      dockerfile: Dockerfile
    container_name: user-profile
    environment:
      - DB_PATH=/user-profile/user-profile.sqlite
      - PORT=3001
    expose:
      - 3001
    networks:
      - web
      - backend
    volumes:
      user-profile-data:/data

  # game:
    # build:
      # context: ../services/game
      # dockerfile: Dockerfile
    # container_name: game
    # environment:
      # - DB_PATH=/game/game.sqlite
      # - PORT=3002
    # expose:
      # - 3002
    # networks:
      # - web
      # - backend
    # volumes:
      # game-data:/data

  volumes:
    user-profile-data:

  networks:
    web:
      driver: bridge
    backend:
      driver: bridge