services:
  reverse-proxy:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - user-profile
      - init-ssl
    networks:
      - web

  init-ssl:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    restart: "no"

  frontend:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - web
    depends_on:
      - user-profile
      # - game

  user-profile:
    build:
      context: ../services/user-profile
      dockerfile: Dockerfile
    container_name: user-profile
    ports:
      - "3001:3001"
    environment:
      - DB_PATH=/data/user-profile.sqlite
      - PORT=3001
      - JWT_SECRET=super-secret-key
    networks:
      - web
      - backend
    volumes:
      - ../services/user-profile/src:/usr/src/app/src   # monte ton code
      - ../services/user-profile/src/data/user-profile.sqlite:/data/user-profile.sqlite  # monte la DB

  # game:
    # build:
      # context: ../services/game
      # dockerfile: Dockerfile
    # container_name: game
    # environment:
      # - DB_PATH=/data/game.sqlite
      # - PORT=3002
    # expose:
      # - 3002
    # networks:
      # - web
      # - backend
    # volumes:
      # - game-data:/data

volumes:
  user-profile-data:

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
